name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.6.9
          - 2.7.5
          - 3.0.3
          - 3.1.1
          - jruby-19mode
    env:
      JRUBY_OPTS: "--2.0"
      USE_SQLITE_EXT: 1
    services:
      postgres:
        image: postgres/postgres
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Build
        run: |
          psql -c 'create database geocoder_test;' -U postgres
          gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
          gem install bundler -v '< 2'
      - name: Tests
        run: bundle exec rake test
